services:
  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql
    environment:
      - POSTGRES_DB=coda
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: ./coda-src
    volumes:
      - ./media:/app/media
      - ./coda-src/static:/app/static
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=715c00f151ab251bc9b82fa18665b84d10b0dc49ac72d9d2fe0a8bcf654fdbb157bd865be9677b52b57dede8605ba8165c71083eca38445ff88d3183f12f6bf35d2d67bf188f7e19d86a489ee5cd51357c5e7661a70344b1469eb96287ff9c8e1c2c3fff
      - RDS_DB_NAME=coda
      - RDS_USERNAME=postgres
      - RDS_HOSTNAME=db
      - RDS_PORT=5432
      - RDS_PASSWORD=postgres
      - DJANGO_DEBUG=True
      - IP_COMPUTADORA=127.0.0.1
      - TUTORIAS_DOMINIO=localhost
      - EMAIL_DOMAIN=a@a.com
      - EMAIL_HOST_PASSWORD=1234
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
