services:
  db:
    build: ./DB
    volumes:
      - ./pgdata:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app_net
  web:
    build: ./coda-src
    volumes:
      - ./media:/app/media
      - ./coda-src/static:/app/static
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=${DJANGO_ENV}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - RDS_DB_NAME=${RDS_DB_NAME}
      - RDS_USERNAME=${RDS_USERNAME}
      - RDS_HOSTNAME=db
      - RDS_PORT=${RDS_PORT}
      - RDS_PASSWORD=${RDS_PASSWORD}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - IP_COMPUTADORA=${IP_COMPUTADORA}
      - LOCAL_HOST_NAME=${LOCAL_HOST_NAME}
      - TUTORIAS_DOMINIO=${TUTORIAS_DOMINIO}
      - EMAIL_DOMAIN=${EMAIL_DOMAIN}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - POSTGRES_NAME=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
