# Generated by Django 4.1.13 on 2025-03-26 20:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=120)),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tutoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BEC', 'Becas'), ('INS', 'Inscripción'), ('ING', 'Inglés'), ('ORG', 'Órgano colegiado'), ('REG', 'Reglamentos'), ('SS', 'Servicio Social'), ('MOV', 'Movilidad'), ('PT', 'Proyecto Terminal'), ('EV', 'Estancia de Verano'), ('TC', 'Trayectoria Curricular'), ('EG', 'Eleccion de grupo'), ('TIT', 'Titulación'), ('EGRE', 'Egreso'), ('PER', 'Personales'), ('SR', 'Seguimiento de reunión'), ('OTRO', 'Otro')], default='SS', max_length=4, verbose_name='SS'), size=None)),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('ACE', 'Aceptada'), ('REJ', 'Rechazada'), ('PEN', 'Pendiente')], default='PEN', max_length=4, verbose_name='PEN')),
                ('asistencia', models.BooleanField(blank=True, default=False, null=True)),
                ('duracion', models.IntegerField(blank=True, default=0, null=True, verbose_name=[(0, 'Menos de 30 minutos'), (1, '30 minutos'), (2, '1 hora'), (3, '2 horas'), (4, 'Más de dos horas')])),
                ('firma_documentos_beca', models.BooleanField(blank=True, default=False, null=True)),
                ('beca_otorgada', models.CharField(blank=True, max_length=255, null=True)),
                ('asesoria_especializada', models.BooleanField(blank=True, default=False, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=1000, null=True)),
                ('impacto_tutoria', models.IntegerField(blank=True, default=0, null=True)),
                ('resultados_tutoria', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
