# Generated by Django 4.1.13 on 2026-05-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorias', '0003_historialcambiotutoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoria',
            name='estado_alumno_historico',
            field=models.IntegerField(blank=True, choices=[('', 'Selecciona un estado'), (1, 'Activo'), (2, 'No reinscrito'), (10, 'Inscrito sin carga académica')], null=True),
        ),
        migrations.AlterField(
            model_name='tutoria',
            name='estado',
            field=models.CharField(choices=[('ACE', 'Aceptada'), ('REJ', 'Rechazada'), ('PEN', 'Pendiente'), ('CAN', 'Cancelada')], default='PEN', max_length=4, verbose_name='PEN'),
        ),
    ]
