# Generated by Django 4.1.13 on 2026-07-31 02:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorias', '0004_tutoria_estado_alumno_historico_alter_tutoria_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoria',
            name='tema',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BEC', 'Becas'), ('INS', 'Inscripción'), ('ING', 'Inglés'), ('ORG', 'Órgano colegiado'), ('REG', 'Reglamentos'), ('SS', 'Servicio social'), ('MOV', 'Movilidad'), ('PT', 'Proyecto terminal'), ('EV', 'Estancia de verano'), ('TC', 'Trayectoria curricular'), ('EG', 'Elección de grupo'), ('TIT', 'Titulación'), ('EGRE', 'Egreso'), ('PER', 'Personales'), ('SR', 'Seguimiento de reunión'), ('REC', 'Recuperación especial'), ('LKR', 'Solicitud de locker'), ('OTRO', 'Otro')], default='SS', max_length=4, verbose_name='SS'), size=None),
        ),
    ]
