# Generated by Django 4.1.13 on 2026-08-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorias', '0005_alter_tutoria_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoria',
            name='fecha_propuesta_1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutoria',
            name='fecha_propuesta_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutoria',
            name='estado',
            field=models.CharField(choices=[('ACE', 'Aceptada'), ('REJ', 'Rechazada'), ('PEN', 'Pendiente'), ('CAN', 'Cancelada'), ('PRO', 'Propuesta')], default='PEN', max_length=4, verbose_name='PEN'),
        ),
    ]
