# Generated by Django 4.1.13 on 2026-08-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorias', '0006_tutoria_fecha_propuesta_1_tutoria_fecha_propuesta_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoria',
            name='motivo_rechazo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
