# Generated by Django 4.1.13 on 2026-08-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorias', '0007_tutoria_motivo_rechazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoria',
            name='estado',
            field=models.CharField(choices=[('ACE', 'Aceptada'), ('REJ', 'Rechazada'), ('PEN', 'Pendiente'), ('CAN', 'Cancelada'), ('PRO', 'Propuesta'), ('VEN', 'Vencida'), ('REP', 'Registrada'), ('REA', 'Realizada')], default='PEN', max_length=4, verbose_name='PEN'),
        ),
    ]
