# Generated by Django 4.1.13 on 2026-08-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorias', '0008_alter_tutoria_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoria',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
