# Generated by Django 4.1.13 on 2026-08-17 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorias', '0009_tutoria_motivo_cancelacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoria',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de solicitud'),
            preserve_default=False,
        ),
    ]
