# Generated by Django 4.1.13 on 2026-08-17 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tutorias', '0010_tutoria_fecha_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoria',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorias_canceladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutoria',
            name='origen_cancelacion',
            field=models.CharField(blank=True, choices=[('ALUMNO', 'Alumno'), ('TUTOR', 'Tutor'), ('SISTEMA', 'Sistema / Vencimiento')], max_length=15, null=True),
        ),
    ]
