# Generated by Django 4.1.13 on 2026-08-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorias', '0013_tutoria_detalle_motivo_cancelacion_y_codigos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoria',
            name='fecha_reporte',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de llenado del reporte'),
        ),
    ]
