# Generated by Django 4.1.13 on 2026-08-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorias', '0014_tutoria_fecha_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoria',
            name='asistencia',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
