# Generated by Django 4.1.13 on 2026-10-03 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0012_trayectoriaversion_and_more'),
        ('Tutorias', '0017_alter_tutoria_estado_alumno_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoria',
            name='trayectoria_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorias_relacionadas', to='Usuarios.trayectoriaversion'),
        ),
    ]
