"""
Django settings for ssocial project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
# settings.py

# TODO mochar esto en prod
# from .env_vars import *

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/
import os
# SECURITY WARNING: keep the secret key used in production secret!
# python3 -c 'import secrets; print(secrets.token_hex(100))'
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']
CSRF_COOKIE_SECURE=False
SESSION_COOKIE_SECURE=False
#SECURE_SSL_REDIRECT=True
#SECURE_HSTS_SECONDS=60
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', os.environ['TUTORIAS_DOMINIO'], os.environ['IP_COMPUTADORA']]
if os.getenv('LOCAL_HOST_NAME'):
    ALLOWED_HOSTS.append(os.environ['LOCAL_HOST_NAME'])

CSRF_TRUSTED_ORIGINS = ['http://'+os.environ['TUTORIAS_DOMINIO']]


#Custom user model
AUTH_USER_MODEL = "Usuarios.Usuario"

# Application definition

INSTALLED_APPS = [
    #External
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'corsheaders',
    'widget_tweaks',
    'import_export',
    'storages',

    #Internal
    'Tutorias.apps.TutoriasConfig',
    'Usuarios',
    'notifications',
]

LOGIN_URL='login'
LOGIN_REDIRECT_URL='login_success'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# TODO Change to False in prod
CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'ssocial.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ssocial.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
# POSTGRESQL DB SETTINGS

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ['RDS_DB_NAME'],
        'USER': os.environ['RDS_USERNAME'],
        'PASSWORD': os.environ['RDS_PASSWORD'],
        'HOST': os.environ['RDS_HOSTNAME'],
        'PORT': os.environ['RDS_PORT'],
        'TIME_ZONE': 'America/Mexico_City',
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True

EMAIL_HOST = os.getenv('NOTIFICATIONS_EMAIL_HOST', 'smtp.gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('NOTIFICATIONS_EMAIL_PASSWORD', os.getenv('EMAIL_HOST_PASSWORD', ''))
EMAIL_HOST_USER = os.getenv('NOTIFICATIONS_EMAIL_USER', 'tutorias.beta.uamc@gmail.com')
EMAIL_PORT = int(os.getenv('NOTIFICATIONS_EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('NOTIFICATIONS_EMAIL_USE_TLS', 'True').strip().lower() in ('1', 'true', 'yes', 'on')
EMAIL_TIMEOUT = int(os.getenv('NOTIFICATIONS_EMAIL_TIMEOUT', '8'))
DEFAULT_FROM_EMAIL = os.getenv('NOTIFICATIONS_EMAIL_FROM', EMAIL_HOST_USER)

# Notificaciones: identidad visual y datos institucionales
NOTIFICATIONS_EMAIL_LOGO_URL = os.getenv('NOTIFICATIONS_EMAIL_LOGO_URL', '')
NOTIFICATIONS_UAM_ADDRESS = os.getenv(
    'NOTIFICATIONS_UAM_ADDRESS',
    'Av. Vasco de Quiroga 4871, Santa Fe Cuajimalpa, Cuajimalpa de Morelos, 05348, Ciudad de Mexico, CDMX',
)
NOTIFICATIONS_UAM_MAPS_URL = os.getenv('NOTIFICATIONS_UAM_MAPS_URL', 'https://maps.google.com/?q=UAM+Cuajimalpa')
NOTIFICATIONS_UAM_PHONE = os.getenv('NOTIFICATIONS_UAM_PHONE', '(55) 5814 6500')
NOTIFICATIONS_CODDAA_PHONE = os.getenv('NOTIFICATIONS_CODDAA_PHONE', '(55) 5814 6500')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'

if os.getenv('DJANGO_ENV') == 'development':
    STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
    STATIC_ROOT = ''  # Desactivar STATIC_ROOT en desarrollo
else:
    STATICFILES_DIRS = []  # En producción, no se usa STATICFILES_DIRS
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")  # `collectstatic` copiará archivos aquí

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
