ARG SEAWEEDFS_VERSION=4.48
FROM chrislusf/seaweedfs:${SEAWEEDFS_VERSION}

USER root
RUN apk add --no-cache openssl

COPY seaweedfs-entrypoint.sh /usr/local/bin/seaweedfs-entrypoint
RUN chmod 0755 /usr/local/bin/seaweedfs-entrypoint

ENTRYPOINT ["/usr/local/bin/seaweedfs-entrypoint"]
CMD ["mini", "-dir=/data", "-s3.port=8333", "-s3.cert.file=/run/seaweedfs-server-tls/server.crt", "-s3.key.file=/run/seaweedfs-server-tls/server.key"]
