# Generated by Django 4.1.13 on 2025-03-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='rfc',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
