# Generated by Django 4.1.13 on 2026-07-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_alumno_rfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coda',
            name='cubiculo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Oficina'),
        ),
        migrations.AlterField(
            model_name='cordinador',
            name='cubiculo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Oficina'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='cubiculo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Oficina'),
        ),
    ]
