# Generated by Django 4.1.13 on 2026-07-31 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_alter_coda_cubiculo_alter_cordinador_cubiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coda',
            name='tema_tutorias',
            field=models.CharField(choices=[('BEC', 'Becas'), ('INS', 'Inscripción'), ('ING', 'Inglés'), ('ORG', 'Órgano colegiado'), ('REG', 'Reglamentos'), ('SS', 'Servicio social'), ('MOV', 'Movilidad'), ('PT', 'Proyecto terminal'), ('EV', 'Estancia de verano'), ('TC', 'Trayectoria curricular'), ('EG', 'Elección de grupo'), ('TIT', 'Titulación'), ('EGRE', 'Egreso'), ('PER', 'Personales'), ('SR', 'Seguimiento de reunión'), ('REC', 'Recuperación especial'), ('LKR', 'Solicitud de locker'), ('OTRO', 'Otro')], default='OTRO', max_length=4),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tema_tutorias',
            field=models.CharField(choices=[('BEC', 'Becas'), ('INS', 'Inscripción'), ('ING', 'Inglés'), ('ORG', 'Órgano colegiado'), ('REG', 'Reglamentos'), ('SS', 'Servicio social'), ('MOV', 'Movilidad'), ('PT', 'Proyecto terminal'), ('EV', 'Estancia de verano'), ('TC', 'Trayectoria curricular'), ('EG', 'Elección de grupo'), ('TIT', 'Titulación'), ('EGRE', 'Egreso'), ('PER', 'Personales'), ('SR', 'Seguimiento de reunión'), ('REC', 'Recuperación especial'), ('LKR', 'Solicitud de locker'), ('OTRO', 'Otro')], default='OTRO', max_length=4),
        ),
    ]
