# Generated by Django 4.1.13 on 2026-08-06 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_alter_coda_tema_tutorias_alter_tutor_tema_tutorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('tutor', 'dia_semana', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
