# Generated by Django 4.1.13 on 2026-08-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0007_pushdevice_installation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='estado',
            field=models.IntegerField(choices=[('', 'Selecciona un estado'), (1, 'Activo'), (2, 'No activo'), (3, 'Suspendido'), (4, 'Baja definitiva'), (5, 'Titulado'), (6, 'Egresado con trámite de certificado'), (7, 'Baja reglamentaria'), (8, 'Egresado potencial'), (9, 'Baja por dictamen de órgano colegiado'), (10, 'Inscrito sin carga académica'), (11, 'Aceptado nuevo ingreso'), (12, 'Egresado sin trámite de certificado'), (13, 'Alumno de nuevo ingreso no presentado'), (14, 'Abandono de más de seis trimestres'), (15, 'Alumno con diploma'), (16, 'Alumno con grado'), (17, 'Admitido en lista complementaria'), (18, 'Estancia terminada (movilidad)'), (19, 'Cancelación del trámite de registro o de ingreso')], null=True),
        ),
    ]
