# Generated by Django 4.1.13 on 2026-10-03 16:19

import Usuarios.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0011_registrar_plantillas_sistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrayectoriaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=Usuarios.models.trayectoria_version_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trayectoria_versiones', to='Usuarios.alumno')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versión de trayectoria',
                'verbose_name_plural': 'Versiones de trayectoria',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='trayectoriaversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('alumno',), name='unique_active_trayectoria_per_alumno'),
        ),
    ]
