from django.db import models

class EventoTutoria(models.TextChoices):
    ALU_AGENDA_POR_QR = 'alu_agenda_por_qr'
    ALU_SOLICITA_TUTORIA = 'alu_solicita_tutoria'
    ALU_AGENDA_TUTORIA = 'alu_agenda_tutoria'
    TUT_ACEPTA_SOLICITUD = 'tut_acepta_solicitud'
    TUT_PROPONE_1_FECHA = 'tut_propone_1_fecha'
    TUT_PROPONE_2_FECHAS = 'tut_propone_2_fechas'
    TUT_RECHAZA_SOLICITUD = 'tut_rechaza_solicitud'
    ALU_SOL_CAMBIO_FECHA_SUG = 'alu_sol_cambio_fecha_sug'
    ALU_SOL_CAMBIO_FECHA_AGEN = 'alu_sol_cambio_fecha_agen'
    ALU_CANCELA_SOLICITUD = 'alu_cancela_solicitud'
    TUTORIA_VENCIDA = 'tutoria_vencida'
    ALU_CANCELA_AGENDADA = 'alu_cancela_agendada'
    TUT_CANCELA_AGENDADA = 'tut_cancela_agendada'
    TUT_REAGENDA_1_FECHA = 'tut_reagenda_1_fecha'
    TUT_REAGENDA_2_FECHAS = 'tut_reagenda_2_fecha'
    TUTORIA_REALIZADA = 'tutoria_realizada'
    ALU_ELIGE_FECHA_PROPUESTA = 'alu_elige_fecha_propuesta'
    PROPUESTA_FECHAS_CANCELADA = 'propuesta_fechas_cancelada'
    TUTORIA_VENCIDA_CANCELADA = 'tutoria_vencida_cancelada'
    TUTORIA_INFORME_REGISTRADO = 'tutoria_informe_registrado'
    ALU_EDITA_INFO_TUTORIA = 'alu_edita_info_tutoria'
